// =======================================================
// * OutputManager
// =======================================================

package reflaxe.output;

#if (macro || reflaxe_runtime)

import haxe.io.BytesBuffer;
import haxe.macro.Context;

import reflaxe.BaseCompiler;

// ---

using Lambda;

using reflaxe.helpers.BaseTypeHelper;
using reflaxe.helpers.NullHelper;

/**
	Describes the complete framework-owned file set from one Reflaxe request.

	The receipt is stored beside generated output. Callers must decode persisted
	JSON through `OutputMetadataCodec` so an untyped JSON value never enters the
	output lifecycle as if it had already been validated.
**/
typedef OutputMetadata = {
	/** The version of the output metadata format for Reflaxe. **/
	version:Int,

	/**
		This value is incremented every time Reflaxe compiles a target.
		Checking if this value has changed can check if Reflaxe has compiled.
	**/
	id:Int,

	/**
		Legacy metadata field retained for schema compatibility.

		Reflaxe now receives and regenerates one complete target program for every
		request, so newly written metadata always records `false`.
	**/
	wasCached:Bool,

	/** A list of file paths to all files generated by the Reflaxe target. **/
	filesGenerated:Array<String>,
}

/**
	Generates one complete target tree and owns its publication lifecycle.

	Directory-shaped output is written through a private
	`DirectoryOutputTransaction`. `outputDir` names the active candidate while
	generation and target completion run; `publicOutputDir` remains the stable
	user-requested path. A successful request publishes the candidate only after
	all target completion work returns. A failed request aborts it without
	modifying the last public tree.
**/
class OutputManager {
	// -------------------------------------------------------
	// constants
	public final GENERATED_LIST_FILENAME = "_GeneratedFiles.json";

	// -------------------------------------------------------
	// fields
	public var compiler(default, null): BaseCompiler;
	/** Active write directory, which is private while a transaction is open. **/
	public var outputDir(default, null): Null<String> = null;
	/** Stable user-requested output directory, independent of transaction paths. **/
	public var publicOutputDir(default, null): Null<String> = null;

	var outputFiles: Array<String> = [];
	var outputMetadata: Null<OutputMetadata> = null;
	var recordedReceipt: Null<OutputMetadata> = null;
	var outputTransaction: Null<DirectoryOutputTransaction>;

	/**
		If any file is modified, created, or deleted, this should be set to `true`.
	**/
	var changed = false;

	/**
		The loaded count value from `_GeneratedFiles.json`.
	**/
	var lastId = -1;

	// -------------------------------------------------------
	// getters
	var options(get, never): BaseCompilerOptions;
	function get_options(): BaseCompilerOptions return compiler.options;

	// -------------------------------------------------------
	// new
	public function new(compiler: BaseCompiler) {
		this.compiler = compiler;
	}

	// -------------------------------------------------------
	// joinPaths
	static function joinPaths(path1: String, path2: String): String {
		return haxe.io.Path.join([path1, path2]);
	}

	// -------------------------------------------------------
	// setOutputDir
	public function setOutputDir(outputDir: String) {
		if(outputTransaction != null) {
			throw "reflaxe:cannot-change-active-output-transaction: Cannot change the output directory while publication is active.";
		}
		publicOutputDir = outputDir;
		this.outputDir = outputDir;
		resetRequestState();
		checkForOldFiles();
	}

	/** Clears mutable generation bookkeeping before loading committed output. **/
	function resetRequestState() {
		outputFiles = [];
		outputMetadata = null;
		recordedReceipt = null;
		changed = false;
		lastId = -1;
	}

	/**
		Starts private output for directory-shaped compiler modes.

		Single-file and manual output retain their existing behavior because they
		do not have one framework-owned directory tree to replace.
	**/
	public function beginOutputTransaction(): Void {
		if(outputTransaction != null) {
			throw "reflaxe:duplicate-output-transaction: Output generation already has an active transaction.";
		}
		if(!options.transactionalFileOutput) {
			return;
		}
		switch(options.fileOutputType) {
			case FilePerModule | FilePerClass: {
				final publicDirectory = publicOutputDir;
				if(publicDirectory == null || publicDirectory.length == 0) {
					throw "reflaxe:missing-output-transaction-path: Directory output requires a non-empty output path.";
				}
				outputDir = publicDirectory;
				resetRequestState();
				checkForOldFiles();
				final transaction = new DirectoryOutputTransaction(publicDirectory);
				outputDir = transaction.begin();
				outputTransaction = transaction;
			}
			case Manual | SingleFile:
		}
	}

	/** Publishes the complete candidate after target completion succeeds. **/
	public function commitOutputTransaction(): Void {
		final transaction = outputTransaction;
		if(transaction == null) {
			return;
		}
		validateTransactionalReceipt();
		transaction.commit();
		outputDir = publicOutputDir;
		outputTransaction = null;
	}

	/** Discards a failed request's private candidate. **/
	public function abortOutputTransaction(): Void {
		final transaction = outputTransaction;
		if(transaction == null) {
			return;
		}
		transaction.abort();
		outputDir = publicOutputDir;
		outputTransaction = null;
	}

	/**
		Old output file management.
	**/
	function checkForOldFiles() {
		if(shouldDeleteOldOutput()) {
			outputMetadata = generatedFilesList();
			lastId = outputMetadata.id ?? -1;
		}
	}

	function shouldDeleteOldOutput() {
		return options.fileOutputType != SingleFile && options.deleteOldOutput;
	}

	function generatedFilesList(): OutputMetadata {
		final path = generatedFilesPath();
		if(sys.FileSystem.exists(path)) {
			return try {
				OutputMetadataCodec.decode(sys.io.File.getContent(path), path);
			} catch(_) {
				defaultGeneratedData();
			}
		}
		return defaultGeneratedData();
	}

	function defaultGeneratedData(): OutputMetadata {
		return {
			version: 1,
			id: 0,
			wasCached: false,
			filesGenerated: []
		};
	}

	function generatedFilesPath() {
		return joinPaths(outputDir.or(""), GENERATED_LIST_FILENAME);
	}

	function ensureOutputDirExists() {
		if(outputDir != null && !sys.FileSystem.exists(outputDir)) {
			sys.FileSystem.createDirectory(outputDir);
		}
	}

	/**
		Generates the output files.
	**/
	public function generateFiles() {
		switch(options.fileOutputType) {
			case Manual: {
				compiler.generateFilesManually();
			}
			case SingleFile: {
				generateSingleFile();
			}
			case FilePerModule: {
				generateFilePerModule();
			}
			case FilePerClass: {
				generateFilePerClass();
			}
		}

		for(path => content in compiler.extraFiles) {
			final keys = [];
			for(priority => cpp in content) {
				if(StringTools.trim(cpp).length > 0) {
					keys.push(priority);
				}
			}

			keys.sort((a, b) -> a - b);

			var result = [];
			for(k in keys) {
				final c = content.get(k);
				if(c != null && StringTools.trim(c).length > 0) {
					result.push(c);
				}
			}

			saveFile(path, result.join("\n\n"));
		}

		if(shouldDeleteOldOutput()) {
			deleteOldOutputFiles();
			recordAllOutputMetadata();
		}
	}

	/**
		Generates a single file.

		This should be able to take no path, a file path, OR a directory path.
	**/
	function generateSingleFile() {
		var filePath = {
			// If output exists and ends with file-extension, it is a direct path
			if(outputDir != null && (options.fileOutputExtension.length == 0 || StringTools.endsWith(outputDir, options.fileOutputExtension))) {
				final file: String = haxe.io.Path.withoutDirectory(outputDir);
				outputDir = haxe.io.Path.directory(outputDir);
				file;
			}
			
			// Otherwise, it is a directory and use the default file name
			else {
				options.defaultOutputFilename;
			}
		}

		if(outputDir != null && outputDir.length > 0) {
			ensureOutputDirExists();
		}

		final arr = [];
		for(o in compiler.generateOutputIterator()) {
			arr.push(o.data);
		}
		saveFile(filePath, joinStringOrBytes(arr));
	}

	function generateFilePerModule() {
		ensureOutputDirExists();

		final files: Map<String, Array<StringOrBytes>> = [];
		for(c in compiler.generateOutputIterator()) {
			final mid = c.baseType.moduleId();
			final filename = overrideFileName(mid, c);
			if(!files.exists(filename)) {
				files[filename] = [];
			}
			final f = files[filename];
			if(f != null) {
				f.push(c.data);
			}
		}

		for(moduleId => outputList in files) {
			saveFile(getFileName(moduleId), joinStringOrBytes(outputList));
		}
	}

	static function joinStringOrBytes(list: Array<StringOrBytes>): StringOrBytes {
		final strings = [];
		final bytes = [];
		for(o in list) {
			switch(o.data()) {
				case String(s): strings.push(s);
				case Bytes(b): bytes.push(b);
			}
		}

		if(strings.length > 0 && bytes.length > 0) {
			throw "Cannot mix String and Bytes outputs for join.";
		}

		return if(strings.length > 0) {
			strings.join("\n\n");
		} else if(bytes.length > 0) {
			final bb = new BytesBuffer();
			for(b in bytes) bb.add(b);
			bb.getBytes();
		} else {
			"";
		}
	}

	function generateFilePerClass() {
		ensureOutputDirExists();
		for(c in compiler.generateOutputIterator()) {
			final filename = overrideFileName(c.baseType.globalName(), c);
			saveFile(getFileName(filename), c.data);
		}
	}

	inline function overrideFileName(defaultName: String, o: {
		var overrideFileName(default, null): Null<String>;
		var overrideDirectory(default, null): Null<String>;
	}) {
		return (o.overrideDirectory != null ? o.overrideDirectory + "/" : "") + (o.overrideFileName ?? defaultName);
	}

	function getFileName(filename: String): String {
		return filename + options.fileOutputExtension;
	}

	/**
		Internal helper function for saving content to a path
		relative to the output folder.
	**/
	public function saveFile(path: String, content: StringOrBytes) {
		if(outputTransaction != null && haxe.io.Path.isAbsolute(path)) {
			throw 'reflaxe:absolute-transaction-output-path: Transactional output path "$path" must be relative to the owned output directory.';
		}
		if(outputTransaction != null) {
			final normalized = haxe.io.Path.normalize(path);
			if(normalized == ".." || StringTools.startsWith(normalized, "../")) {
				throw 'reflaxe:escaping-transaction-output-path: Transactional output path "$path" escapes the owned output directory.';
			}
			path = normalized;
		}
		// Get full path
		final p = if(haxe.io.Path.isAbsolute(path)) {
			path;
		} else if(outputDir != null) {
			joinPaths(outputDir, path);
		} else {
			path;
		}

		// Ensure directories exist
		final dir = haxe.io.Path.directory(p);
		if(!sys.FileSystem.exists(dir)) {
			sys.FileSystem.createDirectory(dir);
		}

		// Save file
		saveFileImpl(p, content);
	}

	function saveFileImpl(path: String, content: StringOrBytes) {
		// Do not save anything if the file already exists and has same content
		if(!sys.FileSystem.exists(path) || !content.matchesFile(path)) {
			content.save(path);
			changed = true;
		}
		if(shouldDeleteOldOutput()) {
			recordOutputFile(path);
		}
	}

	/**
		Records a path for a file that was generated.
		Ensures it will not be deleted when the rest of the old source files are removed.
	**/
	function recordOutputFile(path: String) {
		if(outputDir == null) return;
		final dir = StringTools.endsWith(outputDir, "/") ? outputDir : (outputDir + "/");
		final outputFilePath = StringTools.replace(path, dir, "");
		if(!outputFiles.contains(outputFilePath)) {
			outputFiles.push(outputFilePath);
		}

		if(outputMetadata != null) {
			// -------------------------------------------------------
			// We overwrote this file if it existed, so we can
			// remove it from old files we're planning to delete.
			if(outputMetadata.filesGenerated.contains(outputFilePath)) {
				outputMetadata.filesGenerated.remove(outputFilePath);
			}
		}
	}

	/**
		We've removed elements from this array if we saved
		a new file with the same path, so we can safely assume
		all the remaining elements are old file paths we
		want to delete.
	**/
	function deleteOldOutputFiles() {
		if(outputMetadata != null && outputDir != null) {
			for(file in outputMetadata.filesGenerated) {
				final filePath = joinPaths(outputDir, file);
				if(sys.FileSystem.exists(filePath)) {
					try {
						sys.FileSystem.deleteFile(filePath);
					} catch(e) {
						#if eval
						Context.warning('Could not delete file at "$filePath".\n$e', Context.currentPos());
						#end
					}
				}
			}
		}
	}

	function recordAllOutputMetadata() {
		if(!changed) {
			Sys.println("No files updated.");
		}

		final generatedFiles = outputFiles.copy();
		generatedFiles.sort(Reflect.compare);
		final outputMetadata: OutputMetadata = {
			version: 1,
			id: #if !reflaxe.dont_output_metadata_id lastId + 1 #else 0 #end,
			wasCached: false,
			filesGenerated: generatedFiles,
		};
		recordedReceipt = {
			version: outputMetadata.version,
			id: outputMetadata.id,
			wasCached: outputMetadata.wasCached,
			filesGenerated: outputMetadata.filesGenerated.copy()
		};

		sys.io.File.saveContent(generatedFilesPath(), OutputMetadataCodec.encode(outputMetadata));
	}

	/**
		Checks the framework receipt immediately before directory publication.

		Targets may add separately owned files during `onOutputComplete`, so this
		compares the receipt with the exact framework file set captured when the
		receipt was written rather than with later target-owned additions.
	**/
	function validateTransactionalReceipt(): Void {
		final expected = recordedReceipt;
		final candidateDirectory = outputDir;
		if(expected == null || candidateDirectory == null) {
			throw "reflaxe:missing-output-transaction-receipt: Transactional output did not record its complete framework file set.";
		}
		final path = generatedFilesPath();
		if(!sys.FileSystem.exists(path) || sys.FileSystem.isDirectory(path)) {
			throw 'reflaxe:missing-output-transaction-receipt: Transactional output receipt "$path" is missing.';
		}
		final receipt = OutputMetadataCodec.decode(sys.io.File.getContent(path), path);
		if(receipt.version != expected.version
			|| receipt.id != expected.id
			|| receipt.wasCached != expected.wasCached) {
			throw 'reflaxe:conflicting-output-transaction-receipt: Receipt "$path" changed its version, request id, or cache marker before publication.';
		}
		final actual = receipt.filesGenerated;
		if(actual.length != expected.filesGenerated.length) {
			throw 'reflaxe:conflicting-output-transaction-receipt: Receipt "$path" does not name the complete framework output set.';
		}
		for(index in 0...expected.filesGenerated.length) {
			final expectedFile = expected.filesGenerated[index];
			if(actual[index] != expectedFile) {
				throw 'reflaxe:conflicting-output-transaction-receipt: Receipt "$path" is not the canonical framework output set.';
			}
			final generatedPath = joinPaths(candidateDirectory, expectedFile);
			if(!sys.FileSystem.exists(generatedPath) || sys.FileSystem.isDirectory(generatedPath)) {
				throw 'reflaxe:missing-output-transaction-file: Receipt "$path" names missing output "$expectedFile".';
			}
		}
	}
}

#end
